### ISSUE TITLE
last target on line

### ISSUE THREAD

**Issue by aeosynth** [wellle/targets.vim#215] opened 2018-09-30 03:04 UTC
Hello, I'm a new user, and I was wondering how to operate on the last target on a line? Example:

    the first, the second, the third

if my cursor is at the end of the line and i press `da,`, `the second` target gets deleted; how would I delete `the third` target?

**Comment by wellle** [comment] 2018-09-30 16:59
@aeosynth: Hey, I'll close this as duplicate of https://github.com/wellle/targets.vim/issues/110. Please have a look there to see some discussion on that topic, and feel free to comment there if you have something to add. Thanks!

**Closed by wellle** 2018-09-30 16:59 UTC
