### ISSUE TITLE
In Macvim, ci" overwrites the system clipboard (pasteboard)

### ISSUE THREAD

**Issue by rdlugosz** [wellle/targets.vim#179] opened 2017-07-28 16:59 UTC
Hi - 

It appears that when this plugin is enabled, changing inside double quotes via `ci"` places the changed contents to the system clipboard (accessed via the `"+` register), even when the `clipboard=` setting is unset (this would be expected behavior for all change commands if that was set to something like `clipboard=unnamed`).

**Expected behavior:** Given text inside double quotes, changing it via `ci"` should change the text but not copy the changed text to the system clipbboard.

**What happens instead:** Text in quotes that is changed via `ci"` is copied to the system clipboard.

**In terminal vim and Macvim without this plugin enabled the `ci"` command works as expected.** When this plugin is enabled, Macvim exhibits the unexpected behavior but terminal vim does not.

Here is a screencast demonstrating the unexpected behavior:
https://youtu.be/itNRPoYdDvw

**Comment by wellle** [comment] 2017-09-02 19:28
@rdlugosz: Sorry for the late reply. I just downloaded MacVim to try this. Thank you for taking the time to record a video of the exact setup. I tried exactly the same and in my case it did NOT change the system clipboard value.

Could you try to reproduce it with a vimrc that only include targets.vim? I'm suspecting it might be some interaction between different plugins.

**Comment by fxn** [comment] 2017-09-09 23:53
Just tried, could not reproduce either.

**Comment by rdlugosz** [comment] 2017-09-10 01:14
Hm... must be some other interaction going on then. Feel free to close and
if I get around to trying other combinations of plugins & find the culprit
I'll update this thread.

**Comment by wellle** [comment] 2017-09-11 07:59
Ok I'll close it for now then.

@rdlugosz: Please let me know if you find anything about this issue.

**Closed by wellle** 2017-09-11 07:59 UTC
