### ISSUE TITLE
v4ana not working properly

### ISSUE THREAD

**Issue by NeoHuang** [wellle/targets.vim#134] opened 2016-01-22 09:59 UTC
for following line, when the cursor is at beginning of the line and press `v4ana`, parameter `param4` should be selected, but actually `param3` is selected

``` go
return1, return2 := class.Func(param1, param2, param3, param4)
```

**Comment by wellle** [comment] 2016-01-23 17:46
@NeoHuang: Thanks for bringing this to my attention. I can reproduce the issue and agree that it is unexpected. Here's why it behaves like this:

When operating on arguments, targets.vim only cares about argument boundaries (like `(` and `)`) and argument separators (like `,`). So in our case it looks like this:
```
a, b(c, d, e, f)
```
To find the argument targets, we only check the local context, so it behaves like in this expanded context:
```
g(
a, b(c, d, e, f)
)
```
With the cursor on `a` the first next argument would be `b(c, d, e, f, g)`, the second is `c`, third `d` and fourth `e`.

In order to detect that `b(c, d, e, f)` is no valid argument here, we would need to check if there is actually a surrounding pair of argument boundaries which would basically require to scan the whole document in case there are none. That would be doable, but might be inefficient and so far I liked the locality of the current implementation.

I will think about how we want to deal with this case. Let me know if you have any ideas on this. Thanks again :+1:

**Comment by NeoHuang** [comment] 2016-01-25 10:26
how about checking `=` to break the context?

**Comment by wellle** [comment] 2016-01-25 20:25
Well that would just make it more complex and probably introduce more issues down the line.

Here are a few examples of how `=` (and even `:=`) can be part of valid arguments (and I'd like to keep targets.vim language agnostic):
```go
a("=", b) // string argument (I might handle them in the future)
a(b == c, d) // inline bool argument
a(func(a, b) { c := a; c = b; return a == b; }, d) // function argument
```

**Comment by wellle** [comment] 2018-12-30 16:30
Looks like this has been fixed by the refactorings/improvements in https://github.com/wellle/targets.vim/pull/217 🎉

**Closed by wellle** 2018-12-30 16:30 UTC
