### ISSUE TITLE
`da,` doesn't delete the first parameter

### ISSUE THREAD

**Issue by acornejo** [wellle/targets.vim#143] opened 2016-03-30 20:37 UTC
given the following, if I execute `da,` I would expect it to delete the first element of the list (in this case, oranges), but instead it deletes the second element.

```
cursor position │    ......
buffer line     │    oranges, apples, bananas, tomatoes
selection       │   
```

Perhaps this is the intended behavior, but it certainly feels like a bug.

**Comment by offero** [comment] 2016-04-17 17:10
Just ran into this myself. It also doesn't work at the end of the list. For example, in this python assignment statement:

`a, b, c = 1, 2, 3`

**Comment by wellle** [comment] 2017-09-02 18:11
Closing as duplicate of #110.

@offero: In your example I'm not even sure how `1` could be found. In the simplest implementation that would make the "first" target operational, that would be `a, b, c = 1` in your case, which is probably not helpful. So you would probably expect the `=` to be taken into account somehow, but I'm not sure that should be the responsibility of the separator targets.

**Closed by wellle** 2017-09-02 18:11 UTC
