### ISSUE TITLE
strange behaviour on last item of seperated list

### ISSUE THREAD

**Issue by hoschi** [wellle/targets.vim#116] opened 2015-04-17 09:04 UTC
I have this line:
`a, b, c`
When I place the cursor on `c` and press `da,` I thought it should be:
`a, b`
and the cursor should be on `b`. But I get:
`a, c`
Is this by design, because there is no `,` after `c`?
It would be great to get this working for e.g. JavaScript variable deklarations like:
`var a, b, c;` or in no comma style `var a, b, c`.

**Comment by wellle** [comment] 2015-04-17 16:50
I think this is a duplicate of #110 which addresses the first item, while you talk about the last one. Feel free to comment on that issue instead.

**Closed by wellle** 2015-04-17 16:50 UTC

**Comment by hoschi** [comment] 2015-04-19 18:05
ok
