### ISSUE TITLE
Left in insert mode when no target found.

### ISSUE THREAD

**Issue by stellarhoof** [wellle/targets.vim#197] opened 2017-11-15 03:47 UTC
Using neovim `v0.2.1` with minimal `.vimrc`:
```viml
call plug#begin('$HOME/.local/share/nvim/plugins')

Plug 'https://github.com/wellle/targets.vim'
    let g:targets_seekRanges = 'cr cb cB lc ac Ac lr lb ar ab lB Ar aB Ab rr rb rB ll al Al AB'

call plug#end()
```
In this piece of code
```python
from flask import Flask, request, jsonify
##  cursor ##
app = Flask(__name__)
```
Type `di)` and the editor will be left in insert mode as opposed to normal mode.

**Comment by wellle** [comment] 2017-11-15 09:11
@stellarhoof: I can't reproduce. I just installed neovim v0.2.1 and used exactly your vimrc and the example buffer contents. If I do `dib` from the second line nothing happens and I stay in normal mode. If I do the same from the third line it deletes `__name__` and also leaves in normal mode.

**Comment by stellarhoof** [comment] 2017-11-15 16:58
Ah sorry I assumed it was for every operator. Try `cib`

**Comment by wellle** [comment] 2017-11-15 17:21
Ok, I see the issue now. Thank you, I'll have a look.

**Comment by wellle** [comment] 2017-11-15 22:10
@stellarhoof: Should be fixed now. Thanks again 👍

**Closed** 2017-11-15 22:09 UTC

**Comment by stellarhoof** [comment] 2017-11-15 22:30
Confirmed it now goes back to normal mode. However the cursor shape (`:h 'guicursor'`) doesn't change back.

**Comment by wellle** [comment] 2017-11-15 22:33
Sorry, I haven't used a GUI yet. How exactly can I reproduce that? Looks fine in the terminal.

**Comment by stellarhoof** [comment] 2017-11-16 00:33
No it's not just in the GUI. Neovim uses `'guicursor'` for some terminals as well. I'm using iTerm and with `nvim -u NONE` it defaults to `n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20`. The option is basically a mapping from modes to cursor shapes. I'm not sure why the cursor shape doesn't change in this case, maybe you're switching to normal mode in some unconventional manner? I don't know much about Vim's API.

**Comment by wellle** [comment] 2017-11-16 10:14
Alright, then I fail to reproduce again. Let me see what it looks to me: In normal mode I see the big old block cursor, in insert mode it's the bar and in operator pending mode it's the underscore. So in our example `cib`:
1. I start in normal mode, cursor is block shaped
2. I type `c`, cursor changes to underscore
3. I type `i`, cursor is still underscore
4. I type `b`, cursor changes back to block, just as it was in 1.

<details>
<summary>click here for screenshots</summary>

![screen shot 2017-11-16 at 11 12 05](https://user-images.githubusercontent.com/474504/32885853-13185e26-cabf-11e7-9e2f-dad5da8f9630.png)
![screen shot 2017-11-16 at 11 12 10](https://user-images.githubusercontent.com/474504/32885856-14e209fa-cabf-11e7-8f50-1e8cd603483c.png)
![screen shot 2017-11-16 at 11 12 12](https://user-images.githubusercontent.com/474504/32885857-16564670-cabf-11e7-960a-110d9c010030.png)
![screen shot 2017-11-16 at 11 12 15](https://user-images.githubusercontent.com/474504/32885859-17844d58-cabf-11e7-9fb1-e2f138df5398.png)

</details>

So when you do the same, where does it look different for you?

**Comment by stellarhoof** [comment] 2017-11-16 16:31
Yes, my cursor changes its shape the same way as yours. After further testing I think it has to do with `timeoutlen`. If I finish pressing `cib` before `timeoutlen` has elapsed, the cursor stays in underscore (operator pending mode shape), but the editor is actually in normal mode, whereas if I press `ci` and wait more than `timeoutlen`, then press `b`, the cursor changes back to normal.

**Comment by wellle** [comment] 2017-11-16 17:26
> the cursor stays in underscore

I can't reproduce that. I tried different timings both in minimal vim config (targets.vim only) and `vim -u NONE` and they seem to behave exactly the same for me. Could it be your terminal maybe? I tried in iTerm2.

**Comment by stellarhoof** [comment] 2017-11-16 17:57
It's one of the settings in my iTerm. I tried it fresh and it didn't happen. Will update this issue once I find what it is in case it's helpful for other people.

**Comment by wellle** [comment] 2017-11-16 18:11
Yes please let me know which setting it was, glad we got it sorted 👍

**Comment by stellarhoof** [comment] 2017-11-16 18:34
Actually it was not iTerm's configuration. It was tmux. It exhibits the behavior with tmux 2.6, no custom configuration in `.tmux.conf`. I use `fish`, but it also happens with `bash`. Couldn't find anything on neovim's issues with the search query `cursor tmux`.

**Comment by wellle** [comment] 2017-11-16 23:07
Oh that's very interesting. I'll try to upgrade tmux and reproduce this issue over the weekend.

**Comment by stellarhoof** [comment] 2017-11-17 00:28
Thank you for all the hard work 👍

**Comment by wellle** [comment] 2017-11-26 13:08
@stellarhoof: Ok, so I upgradet to tmux 2.6, opened a fresh session with an empty .tmux.conf, started neovim 0.2.1, inserted some characters and then back in normal mode typed `cib` in various different speeds. I tried the same with vim 8.0.249, and in no case could I reproduce ending up in insert mode anymore. And in Neovim it always ended up with the expected block cursor shape.
